version: "3"
services:

  db:
    image: wufei0610/postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    volumes:
      - /application/wikijs/data:/var/lib/postgresql/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "20"

  wiki:
    image: wufei0610/wikijs
    container_name: wikijs
    hostname: wikijs
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
      #SSL_ACTIVE: 1
      #LETSENCRYPT_DOMAIN: wiki.sinux.com
      #LETSENCRYPT_EMAIL: wufei@sinux.com.cn
    restart: always
    ports:
      - "9010:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "20"

