apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
  labels:
    name: pv3
spec:
  nfs:
# path 挂载路径
    path: /nfs/data3
# server nfs机器的ip
    server: 192.168.3.245
# ReadWriteOnce能以读写模式被加载到一个节点上
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: "Recycle"
  #  accessModes: ["ReadOnlyMany"]
  capacity:
    storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4
  labels:
    name: pv4
spec:
  nfs:
    path: /nfs/data4
    server: 192.168.3.245
# ReadOnlyMany以只读模式加载到多个节点上
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: "Retain"
  #accessModes: ["ReadOnlyMany"]
  capacity:
    storage: 20Gi
---    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5
  labels:
    name: pv5
spec:
  nfs:
    path: /nfs/data5
    server: 192.168.3.245
# ReadOnlyMany以只读模式加载到多个节点上
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: "Retain"
  #accessModes: ["ReadOnlyMany"]
  capacity:
    storage: 50Gi
